services:
  - type: web
    name: gym-backend
    runtime: node
    plan: free
    buildCommand: npm ci --include=dev && npm run prisma:generate && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /api/docs
    envVars:
      - key: NODE_ENV
        value: production
      - key: TZ
        value: America/La_Paz
      - key: DATABASE_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: JWT_ACCESS_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: FRONTEND_URL
        sync: false
